# Generated by Django 4.1 on 2022-09-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('text', models.CharField(max_length=1000)),
                ('text_en', models.CharField(max_length=1000, null=True)),
                ('text_ru', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'AboutUs',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('photo', models.ImageField(upload_to='company_photo/')),
                ('information', models.TextField()),
                ('information_en', models.TextField(null=True)),
                ('information_ru', models.TextField(null=True)),
                ('key_words', models.CharField(max_length=255, null=True)),
                ('web_site', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_en', models.CharField(blank=True, max_length=255, null=True)),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('location', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('text', models.CharField(max_length=1000)),
                ('text_en', models.CharField(max_length=1000, null=True)),
                ('text_ru', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Main',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='product_photo/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_photos', to='web_app.company')),
            ],
        ),
    ]
