# Generated by Django 4.1 on 2022-09-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
