# Generated by Django 4.1 on 2022-08-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_contact_address_en_contact_address_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(upload_to='company_photo/'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(upload_to='product_photo/'),
        ),
    ]
